# Generated by Django 3.0.3 on 2020-08-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='organization_website',
            field=models.URLField(default='apple.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_request',
            name='item_description',
            field=models.CharField(default='No description provided', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_request',
            name='item_quantity',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item_request',
            name='item_return',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
