# Generated by Django 3.0.3 on 2020-08-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200815_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='organization_website',
            field=models.URLField(max_length=100),
        ),
    ]
